version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout  # Pobieranie kodu źródłowego
      - run:
          name: Instalacja zależności
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt  # Instalowanie zależności
      - run:
          name: Uruchamianie testów
          command: |
            . venv/bin/activate
            python -m unittest discover  # Uruchamianie testów jednostkowych

workflows:
  version: 2
  build_test:
    jobs:
      - build
