version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Uruchomienie testów
          command: |
            python -m unittest discover

  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - run:
          name: Deploy aplikacji
          command: |
            echo "Deploying app 3..."
            sleep 1
            echo "Deploying app 2..."
            sleep 1
            echo "Deploying app 1..."
            sleep 1
            echo "Deployed"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
