version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout  # Pobieranie kodu źródłowego
      - run:
          name: Uruchamianie testów
          command: |
            python -m unittest discover

workflows:
  version: 2
  build_test:
    jobs:
      - build
